### ISSUE TITLE
Access for webots_ros2 team

### ISSUE THREAD

**Issue by nuclearsandwich** [ros2-gbp/webots_ros2-release#1]
Continuing the discussion from https://github.com/ros/rosdistro/pull/31123#discussion_r743456445

Adding the following maintainers
* @omichel 
* @BenjaminHug8
*  @stefaniapedrazzi
*  @BenjaminDeleze
*  @ad-daniel

Invitations to join the ros2-gbp organization and team should go out later today.

The histories of the two release repositories appear to be mutually divergent so I pushed all of the tags and only the tags from the cyberbotics release repository to the ros2-gbp repository which will allow the latter to provide any tags from the release history although the individual branch histories of the ros2-gbp repository will not include each release. I think this is the best non-destructive solution.

Once each of you have accepted the invitation and confirmed access you can re-run the galactic bloom release PR with the updated release repo url using:

```
bloom-release -r galactic --pull-request-only webots_ros2 --override-release-repository-url https://github.com/ros2-gbp/webots_ros2-release
```
The existing PR and this issue can then be closed.

**Comment by BenjaminHug8** [comment]
After running the command, the `Nosetests` fail with an error `No ROSGHPRB_TOKEN set, continuing without checking hooks` (see this [PR](https://github.com/ros/rosdistro/pull/31155)).

Did I miss something in configuration to create this token (I create a personal token for bloom)?

**Comment by BenjaminHug8** [comment]
Nvm, it is an `.git` missing.

**Comment by BenjaminHug8** [comment]
I am investigating on issues for packages we deleted but still linked (for example `webots_ros2_abb`).

**Comment by BenjaminHug8** [comment]
Actually I have 2 issues:

1) I want to use the branch `master` with tag `1.1.3` in order to make releases for foxy rolling and galactic, but I can only achieve to have an older tag `1.1.2` when trying to make those releases.

2) We deleted some sub-packages but when a release is created for Galactic, the tests on the bloom PR complain that it cannot find the sub-packages deleted, how can I force it to know that those packages are deleted ?
(https://github.com/ros/rosdistro/runs/4138016559?check_suite_focus=true#step:6:1927)

**Comment by BenjaminHug8** [comment]
> Actually I have 2 issues:
> 
>     1. I want to use the branch `master` with tag `1.1.3` in order to make releases for foxy rolling and galactic, but I can only achieve to have an older tag `1.1.2` when trying to make those releases.
> 
>     2. We deleted some sub-packages but when a release is created for Galactic, the tests on the bloom PR complain that it cannot find the sub-packages deleted, how can I force it to know that those packages are deleted ?
>        (https://github.com/ros/rosdistro/runs/4138016559?check_suite_focus=true#step:6:1927)

Question 1) has been solved by changing the `tracks.yaml` file in `master` branch (btw would it be possible to make `master` the default branch ?).

For question 2) I updated the `distribution.yaml` file by hand and removing the deleted packages worked for Galactic with version `1.1.2` but when I added the missing ones it complains only for [Foxy](https://github.com/ros/rosdistro/pull/31160) with `1.1.3` (tag not merged on our foxy branch, but we want to try to use only `master` for multiple ROS distribution). It seems to not recognize the tag (version `1.1.3`).

**Comment by BenjaminHug8** [comment]
Tried to solve [Foxy](https://github.com/ros/rosdistro/pull/31161) with increment of Version = `1` instead of `2` in `track.yml` and used this command:

    bloom-release -r foxy --pull-request-only webots_ros2 --override-release-repository-url https://github.com/ros2-gbp/webots_ros2-release.git --edit --track foxy --new-track

Still have an [error](https://github.com/ros/rosdistro/runs/4140860249?check_suite_focus=true#step:6:226).

I am no quite sure if we are supposed to first have branches with foxy release on this repo before being able to pass the test in the PR of RosDistro.

EDIT: I will try with a merge of our `master` branch in `foxy` branch.

**Comment by BenjaminHug8** [comment]
@nuclearsandwich do you have an idea why when I make a release for `Foxy` old deleted packages are coming back and the new ones are deleted ? Does it has something to do with the default branch of this repo ?

Here is an example, where `webots_ros2_abb` has been deleted and `webots_ros2_control` has been added:
```
         packages:
         - webots_ros2
  -      - webots_ros2_control
  +      - webots_ros2_abb
         - webots_ros2_core
  -      - webots_ros2_driver
  +      - webots_ros2_demos
         - webots_ros2_epuck
  +      - webots_ros2_examples
         - webots_ros2_importer
  -      - webots_ros2_mavic
         - webots_ros2_msgs
         - webots_ros2_tesla
  -      - webots_ros2_tests
         - webots_ros2_tiago
         - webots_ros2_turtlebot
  +      - webots_ros2_tutorials
         - webots_ros2_universal_robot
```

Also I am unable to make a release for the new version 1.1.3 for `Foxy`, but I achieved to do a  release for the version 1.1.2 created before the change of repo for `Galactic`.

[Here](https://github.com/ros/rosdistro/pull/31173) is my PR for the release of `Foxy`, merging `master` into `foxy` did not have any impact.

**Comment by BenjaminHug8** [comment]
> @nuclearsandwich do you have an idea why when I make a release for `Foxy` old deleted packages are coming back and the new ones are deleted ? Does it has something to do with the default branch of this repo ?
> 
> Here is an example, where `webots_ros2_abb` has been deleted and `webots_ros2_control` has been added:
> 
> ```
>          packages:
>          - webots_ros2
>   -      - webots_ros2_control
>   +      - webots_ros2_abb
>          - webots_ros2_core
>   -      - webots_ros2_driver
>   +      - webots_ros2_demos
>          - webots_ros2_epuck
>   +      - webots_ros2_examples
>          - webots_ros2_importer
>   -      - webots_ros2_mavic
>          - webots_ros2_msgs
>          - webots_ros2_tesla
>   -      - webots_ros2_tests
>          - webots_ros2_tiago
>          - webots_ros2_turtlebot
>   +      - webots_ros2_tutorials
>          - webots_ros2_universal_robot
> ```
> 
> Also I am unable to make a release for the new version 1.1.3 for `Foxy`, but I achieved to do a release for the version 1.1.2 created before the change of repo for `Galactic`.
> 
> [Here](https://github.com/ros/rosdistro/pull/31173) is my PR for the release of `Foxy`, merging `master` into `foxy` did not have any impact.

Nvm I was using the `--pull-request-only`. Not using it enables to make new releases (see [here](https://github.com/ros/rosdistro/pull/31176)).

**Comment by BenjaminHug8** [comment]
@omichel should we close this issue as we succeed to make a new release for `Galactic` and `Foxy` ?

**Comment by omichel** [comment]
The only open question I have here is whether the main branch of this repo should be changed to [master](https://github.com/ros2-gbp/webots_ros2-release/tree/master). It seems a bit strange to have on [debian/galactic/focal7webots_ros2_abb](https://github.com/ros2-gbp/webots_ros2-release/tree/debian/galactic%2Ffocal%2Fwebots_ros2_abb), isn't it?

**Comment by nuclearsandwich** [comment]
> do you have an idea why when I make a release for `Foxy` old deleted packages are coming back and the new ones are deleted ? Does it has something to do with the default branch of this repo ?

I'm investigating a similar report right now. I should make the issue public so folks can follow it. I know what's happening but not yet the why or the what-changed. I'll link back here with what I find.



> The only open question I have here is whether the main branch of this repo should be changed to [master](https://github.com/ros2-gbp/webots_ros2-release/tree/master). It seems a bit strange to have on [debian/galactic/focal7webots_ros2_abb](https://github.com/ros2-gbp/webots_ros2-release/tree/debian/galactic%2Ffocal%2Fwebots_ros2_abb), isn't it?

Yeah that's a side effect of the ros2-gbp creation process, the first branched pushed to GitHub becomes the default branch and Git pushes are lexically ordered when using `git push --all`. I'll update the default branch now.

**Comment by BenjaminHug8** [comment]
> > do you have an idea why when I make a release for `Foxy` old deleted packages are coming back and the new ones are deleted ? Does it has something to do with the default branch of this repo ?
> 
> I'm investigating a similar report right now. I should make the issue public so folks can follow it. I know what's happening but not yet the why or the what-changed. I'll link back here with what I find.

This has been solved on my side when creating the new release of `Foxy` without the `--pull-request-only`. When I tried to make the release of `Galactic` with the `--pull-request-only` on the same version we wanted to release on our repo I had this issue.

> > The only open question I have here is whether the main branch of this repo should be changed to [master](https://github.com/ros2-gbp/webots_ros2-release/tree/master). It seems a bit strange to have on [debian/galactic/focal7webots_ros2_abb](https://github.com/ros2-gbp/webots_ros2-release/tree/debian/galactic%2Ffocal%2Fwebots_ros2_abb), isn't it?
> 
> Yeah that's a side effect of the ros2-gbp creation process, the first branched pushed to GitHub becomes the default branch and Git pushes are lexically ordered when using `git push --all`. I'll update the default branch now.

Perfect thank you!

**Comment by nuclearsandwich** [comment]
> Nvm I was using the `--pull-request-only`. Not using it enables to make new releases (see [here](https://github.com/ros/rosdistro/pull/31176)).

So I'm now not quite sure whether the issue I'm investigating is part of this. The `--pull-request-only` flag skips doing new bloom generation and instead looks at the current state of the specified track and tries to create a pull request that updates the rosdistro to that state. It's useful for starting the automatic PR generation over again if, for example, a GitHub auth issue causes the initial PR creation to fail. I recommended it in this case since the bloom release was already performed and pushed to the previous release repository, so that once I moved the content here, the only need would be to recreate the PR to use this release repository for all the same release artifacts. However the `--pull-request-only` flag isn't suitable for new releases since it won't generate new artifacts.

Was the release into Foxy being performed a new release or was it just being done to update the release repo info? I would expect the latter case to work but not the former.

**Comment by BenjaminHug8** [comment]
> Was the release into Foxy being performed a new release or was it just being done to update the release repo info? I would expect the latter case to work but not the former.

Yes the release into Foxy was a new release and not simply updating the release info.

**Comment by nuclearsandwich** [comment]
> Yes the release into Foxy was a new release and not simply updating the release info.

Got it. My apologies for the unintended misinformation.
