### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by omichel** [ros2-gbp/webots_ros2-release#2]
Following #1, may I ask you to add @ygoumaz as a maintainer?

Thank you.

*Note*: if you wish, you may also remove @BenjaminHug8 as he is not any more working with us.

**Comment by omichel** [comment]
@nuclearsandwich: any update on this one?

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich: any update on this one?

Thanks for the ping omichel. I missed the issue assignment here. Mentions are always going to be more reliable for me due to the way I triage my GitHub notifications. I've opened https://github.com/ros2-gbp/ros2-gbp-github-org/pull/137 to make this change.

**Comment by omichel** [comment]
Thank you.
